// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozpwjblygfqpdspntbkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cHdqYmx5Z2ZxcGRzcG50YmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDcwNjYsImV4cCI6MjA3MDAyMzA2Nn0.6ucyUYBI02-28PaTG3ybzYZvXlUC8Zeh9XpDw7JTlOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});